### ISSUE TITLE
Cannot open Plots.uxf ?

### ISSUE THREAD

**Issue by arwild01** [umlet/umlet#259]
I recently installed release 13.2 into "Nvidia Nsight Eclipse Edition 6.5" (which is actually a re-branded Eclipse 3.8) on on CentOS Linux 6.6.

During startup of "nsight" I get teh following backtrace:

     2 | ERROR | com.baselet.diagram.io.DiagramFileHandler - "Cannot open the file: /apps_hpc/cuda/6.5.14/libnsight/configuration/org.eclipse.osgi/bundles/93/1/.cp/palettes/Plots.uxf"
java.lang.NullPointerException
        at com.baselet.diagram.io.InputHandler.endElement(InputHandler.java:83)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1742)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2900)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:607)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:489)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:835)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1210)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:568)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:302)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
        at com.baselet.diagram.io.DiagramFileHandler.doOpen(DiagramFileHandler.java:251)
        at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:74)
        at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:58)
        at com.baselet.diagram.PaletteHandler.<init>(PaletteHandler.java:12)
        at com.baselet.control.Main.getPalettes(Main.java:431)
        at com.baselet.gui.BaseGUIBuilder.newPalettePanel(BaseGUIBuilder.java:108)
        at com.baselet.gui.BaseGUIBuilder.initBase(BaseGUIBuilder.java:44)
        at com.baselet.plugin.gui.EclipseGUIBuilder.initEclipseGui(EclipseGUIBuilder.java:52)
        at com.baselet.plugin.gui.Editor$2.run(Editor.java:83)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:241)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:721)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:682)
        at java.awt.EventQueue$3.run(EventQueue.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:691)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

The file in question exists and I do have permissions to read the file:

    [arwild1@hplcnlsp8 ~]$ ls -ld /apps_hpc/cuda/6.5.14/libnsight/configuration/org.eclipse.osgi/bundles/93/1/.cp/palettes/Plots.uxf
    -rw-r--r-- 1 arwild1 hpc_br 4538 Apr 22 09:04 /apps_hpc/cuda/6.5.14/libnsight/configuration/org.eclipse.osgi/bundles/93/1/.cp/palettes/Plots.uxf
    [arwild1@hplcnlsp8 ~]$ head /apps_hpc/cuda/6.5.14/libnsight/configuration/org.eclipse.osgi/bundles/93/1/.cp/palettes/Plots.uxf 
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <diagram program="umlet" version="12.1">
      <help_text>// Uncomment the following line to change the fontsize and font:
    fontsize=10
    // fontfamily=SansSerif //possible: SansSerif,Serif,Monospaced
    
    
    //////////////////////////////////////////////////////////////////////////////////////////////
    // Welcome to UMLet!
    //

Once insight the application, I can create a New file and then create a new "umlet diagram".  I do see the work surface and several toolbars so it's not clear to me if something is really not working "correctly per se.  

Here's a screenshot:

![umlet_nsight](https://cloud.githubusercontent.com/assets/3150609/7277374/47eb3e3a-e8d5-11e4-911b-6e27cf85635d.png)

**Comment by afdia** [comment]
Please check if there is a "Plots" palette in the dropdown list (should be between "UML Use Case" and "Deprecated - UML Activity")

I don't know exactly why this is only happening in this specific Eclipse variation, but the line of code in the stacktrace is the same as in #244.
Perhaps this is just some kind of racing condition issue where the GUI is not initialized when the Plots.uxf palette entry is parsed and therefore a NPE is thrown.
Perhaps the fix of #244 also works for this issue, but I will let this issue open until the next release.

**Comment by afdia** [comment]
can you reproduce the issue in v13.3 or is it fixed?

**Comment by arwild01** [comment]
I apologize taking so long to follow up on this.

There is a "Plots" item in the drop down, but after I select it the window
is "blank".

[image: Inline image 1]

I'll be testing 13.3.0 shortly.

-Alan

On Sun, May 3, 2015 at 12:02 PM, afdia <notifications@github.com> wrote:

> Please check if there is a "Plots" palette in the dropdown list (should be
> between "UML Use Case" and "Deprecated - UML Activity")
>
> I don't know exactly why this is only happening in this specific Eclipse
> variation, but the line of code in the stacktrace is the same as in #244
> <https://github.com/umlet/umlet/issues/244>.
> Perhaps this is just some kind of racing condition issue where the GUI is
> not initialized when the Plots.uxf palette entry is parsed and therefore a
> NPE is thrown.
> Perhaps the fix of #244 <https://github.com/umlet/umlet/issues/244> also
> works for this issue, but I will let this issue open until the next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umlet/umlet/issues/259#issuecomment-98504660>.
>



-- 
alan@madllama.net http://humbleville.blogspot.com

**Comment by arwild01** [comment]
Happy to report it appears fixed in 13.3

-Alan

**Comment by afdia** [comment]
good to hear :)
