### ISSUE TITLE
Umlet doesn't work with Ubuntu when jayatana is installed

### ISSUE THREAD

**Issue by afdia** [umlet/umlet#312]
A user reported that UMLet 13.3 doesn't work with Ubuntu if jayatana is installed.
v12.2 still works (therefore perhaps it has to do with the switch to RSyntaxPane for the properties panel)

Until the issue is fixed, anyone experiencing the issue should either remove jayatana (sudo apt-get remove jayatana) or temporily disable it as described in: http://stackoverflow.com/a/30201976

Stacktrace of the error:
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at java.util.Hashtable.put(Hashtable.java:514)
at javax.swing.JEditorPane.registerEditorKitForContentType(JEditorPane.java:1247)
at javax.swing.JEditorPane.registerEditorKitForContentType(JEditorPane.java:1229)
at javax.swing.JEditorPane.loadDefaultKitsIfNecessary(JEditorPane.java:1307)
at javax.swing.JEditorPane.getKitTypeRegistry(JEditorPane.java:1264)
at javax.swing.JEditorPane.createEditorKitForContentType(JEditorPane.java:1189)
at javax.swing.JEditorPane.getEditorKitForContentType(JEditorPane.java:1088)
at javax.swing.JEditorPane.setContentType(JEditorPane.java:979)
at javax.swing.JEditorPane.handleConnectionProperties(JEditorPane.java:783)
at javax.swing.JEditorPane.getStream(JEditorPane.java:757)
at javax.swing.JEditorPane.setPage(JEditorPane.java:435)
at com.baselet.diagram.StartUpHelpText.showHTML(StartUpHelpText.java:89)
at com.baselet.diagram.StartUpHelpText.<init>(StartUpHelpText.java:56)
at com.baselet.diagram.DiagramHandler.initStartupTextAndFileDrop(DiagramHandler.java:94)
at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:66)
at com.baselet.diagram.DiagramHandler.<init>(DiagramHandler.java:58)
at com.baselet.control.Main.doNewHelper(Main.java:338)
at com.baselet.control.Main.access$1(Main.java:333)
at com.baselet.control.Main$2.run(Main.java:328)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
at java.awt.EventQueue.access$200(EventQueue.java:103)
at java.awt.EventQueue$3.run(EventQueue.java:694)
at java.awt.EventQueue$3.run(EventQueue.java:692)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by kno10** [comment]
jayatana seems to break EVERYTHING.

The solution is simple: uninstall jayatana. Don't blame other applications for not fixing jayatana bugs.
