### ISSUE TITLE
No main manifest attribute 

### ISSUE THREAD

**Issue by hbeygel** [umlet/umlet#384]
when trying to run on Mac OSX 10.11.4 with eclipse installed getting:
"no main manifest attribute, in com.umlet.plugin-14.2.jar"

**Comment by afdia** [comment]
Thanks for the report
Is the problem only in 14.2 or in previous versions too?

**Comment by hbeygel** [comment]
same error for 14.1

error for 13.3 :
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at com.baselet.control.Main.<clinit>(Main.java:55)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by afdia** [comment]
Ok let's focus on the v14.2 for the moment.

Please try the following procedure to make sure the issue is the umlet plugin itself and not the specific Eclipse version or other plugins:
1. Download "Eclipse IDE for Java Developers" and unzip it
2. Copy the "com.umlet.plugin-14.2.jar" into the **eclipse /dropins** directory
3. Start Eclipse and use a fresh workspace
4. Create a project and add an uxf file

Does it still show the error? A quick google search has shown that the cause is a missing Main-Class attribute in the manifest which is not required for Eclipse Plugins.
