### ISSUE TITLE
RuntimeException in MainStandalone#printUsage

### ISSUE THREAD

**Issue by barthel** [umlet/umlet#493]
If I start UMLet (v. 14.2, standalone)  and passing only the ```-format=svg``` command line argument, then the following exception is shown:
```
$ java -Dsun.java2d.xrender=f -jar ./umlet.jar -format=svg
Exception in thread "main" java.lang.RuntimeException: Program must be initialized before using it
	at com.baselet.control.enums.Program.getInstance(Program.java:17)
	at com.baselet.standalone.MainStandalone.printUsage(MainStandalone.java:236)
	at com.baselet.standalone.MainStandalone.main(MainStandalone.java:92)
```

**Comment by afdia** [comment]
Thanks for the report, this has been fixed some time ago in be31d6f36ba0ac726152fcbfaa9c063d37198cd3 but it seems that there was no issue for it

After the fix you will see the following message:
```
USAGE: -action=convert -format=(pdf|svg|eps|bmp|jpg|wbmp|jpeg|png|gif) -filename=inputfile.uxf [-output=outputfile[.extension]]
```
