### ISSUE TITLE
Unable to exit if the user is unable to delete the file /tmp/umlet.tmp (standalone mode)

### ISSUE THREAD

**Issue by fjtc** [umlet/umlet#535]
If the file **/tmp/umlet.tmp** exists and is not owned by the current user running **UMLet**, the close command will not work (you will be unable to close the application unless you kill it) and the following exception will be outputted to the console:

```
Gtk-Message: 16:02:51.603: Failed to load module "canberra-gtk-module"
Exception in thread "AWT-EventQueue-1" java.lang.RuntimeException: Cannot delete file /tmp/umlet.tmp
	at com.baselet.control.util.Path.safeDeleteFile(Path.java:182)
	at com.baselet.standalone.gui.StandaloneGUI.closeWindow(StandaloneGUI.java:78)
	at com.baselet.standalone.gui.SwingWindowListener.windowClosing(SwingWindowListener.java:19)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

When this happens, it is necessary to delete **/tmp/umlet.tmp** manually or the same error will happen over and over.

I'm not sure if this file is actually used but, if so, it would be better to change its name to something else that is related to the user that is running it. This is necessary because, in the event that more than 1 user starts **UMLet** in the same machine, only the first to start it will get the expected close behavior. The other will be unable to close it until the first user closes the process and deletes his/her **/tmp/umlet.tmp**.

**Comment by fjtc** [comment]
I don't have  the time to fix this issue myself but I noticed that a very simple modification in the method
**com.baselet.standalone.MainStandalone.tmpFile()** should do the trick.

I suggest changing this code from:

```java
	private static File tmpFile() {
		return new File(Path.temp() + Program.getInstance().getProgramName().toLowerCase() + ".tmp");
	}
```

to something like:

```java
	private static File tmpFile() {
		return new File(Path.temp() + Program.getInstance().getProgramName().toLowerCase() +  "-" + System.getProperty("user.name") + ".tmp");
	}
```

This should associate this file with the current user, allowing a single copy per user but multiple copies from distinct users to run on the same machine. What do you think?

**Comment by afdia** [comment]
Hi

The file is used to determine if umlet is currently running. E.g. if you doubleclick a uxf file and umlet is assigned for uxf files, it will open Umlet and the diagram. If you click on another file, it will open the diagram in the running instance instead of opening another one.

I have added your suggestion because this logic is only useful per user, so including the username in the filename is OK, although I strip out any characters which may be invalid for filesystems.
