### ISSUE TITLE
Setting an element's BG|FG using context/popup menu doesn't work

### ISSUE THREAD

**Issue by 911992** [umlet/umlet#605]
Problem related to snapshot/current milestone probably.

The bug(producing):
* click on an element, then change the background/foreground to any color

Related stacktrace:
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: com.baselet.diagram.draw.helper.theme.Theme$PredefinedColor
s cannot be cast to java.lang.String
        at com.baselet.gui.menu.MenuFactory$1.run(MenuFactory.java:218)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

The possible issue is when non-`String` content is added into swing-level menu, while the [`MenuFactory`](https://github.com/umlet/umlet/blame/master/umlet-swing/src/main/java/com/baselet/gui/menu/MenuFactory.java#L217)
 is expecting `String`

Related commit: [30d818eb3444e0119bb12e00035503f7507a84e3](https://github.com/umlet/umlet/commit/30d818eb3444e0119bb12e00035503f7507a84e3) / #585  
Where `enum` element is added/returned, instead of string value.

The fix is about calling `toString()` instead of exceptionable `(String)` casting.

Related pull request: #603

**Comment by afdia** [comment]
thanks for your fix!
the issue was probably introduced during the extraction of the colors into themes for the new umlet vscode plugin
