### ISSUE TITLE
umlet standalone window not showing up on windows 10

### ISSUE THREAD

**Issue by robibobi** [umlet/umlet#672]
When i start umlet, the applications starts but the window is not visible. When i click on the umlet Tab on the taskbar, the window is not shown. When i press Alt + TAB to open the window switcher, the umlet windows is shown but with blank white content.

![image](https://user-images.githubusercontent.com/9533401/158950706-1cb03280-b050-4b1e-b607-0f4ead97b33e.png)

I tried with standalone version 14.3.0, 14.2, and 14.1.1 and none of them worked.

I added some logging configuration as explained in [this issue](https://github.com/umlet/umlet/issues/545). But there is no exception or error log when i start umlet using the command line. This is the logging output:

```
❯ java "-Dlog4j.configuration=file:log4j.properties" -jar umlet.jar
2022-03-18 07:23:44,614 |      0 | INFO  | com.baselet.control.enums.Program | Initializing Program: Version=14.3.0, Runtime=STANDALONE
2022-03-18 07:23:44,683 |     69 | INFO  | com.baselet.control.Main       | Initializing GUI ...
2022-03-18 07:23:46,285 |   1671 | INFO  | com.baselet.control.Main       | GUI initialized
```
Im Running windows 10 Version 10.0.19044
Here is my java version:
```
❯ java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
```
Do you have an idea how to solve this issue?

**Comment by afdia** [comment]
Hi

I have not experienced that issue (and I dont remember someone reporting the exact behavior).
Maybe check that your user has read/write access to the Umlet dir and its subdirs.

Another alternative would be to use www.umletino.com which supports most of Umlets features but runs in the browser

**Comment by zocker-160** [comment]
The same happens on Linux as well when running with Java 8.

Upgrading to Java 17 fixes the issue, so I think that could be a solution for Windows as well.

**Comment by robibobi** [comment]
> Hi
> 
> I have not experienced that issue (and I dont remember someone reporting the exact behavior). Maybe check that your user has read/write access to the Umlet dir and its subdirs.
> 
> Another alternative would be to use [www.umletino.com](http://www.umletino.com) which supports most of Umlets features but runs in the browser

Thanks for your response. My user has read/write access on the directory. I also tried different directories but with no luck.
I use Umletino now as a workarround. 

> The same happens on Linux as well when running with Java 8.
> 
> Upgrading to Java 17 fixes the issue, so I think that could be a solution for Windows as well.

Do you mean the Java 17 JDK? I gave it a try and installed it. Unfortunately it did not solve the problem.

**Comment by ckaiser79** [comment]
Its been a while, but I ran into the same error. I see a failed update check in the startup log (which is blocked by a firewall). 

```
C:\devel\opt\Umlet>C:\coprogramme\java\jdk-11.0.14.1+1\bin\java.exe -D"log4j.configuration=file:log4j.properties" -jar umlet.jar
INFO  Program - Initializing Program: Version=15.0.0, Runtime=STANDALONE
INFO  Main - Initializing GUI ...
INFO  Main - GUI initialized
ERROR StartUpHelpText - Error at checking for new UMLet version
java.net.UnknownHostException: www.umlet.com
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/java.net.Socket.connect(Socket.java:558)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpCli
```

**Comment by zocker-160** [comment]
Looks like an unhandled exception which needs fixing in the code. I can look into it if umlet dev does not respond.

**Comment by afdia** [comment]
Unfortunately the stacktrace seems to be incomplete (because there is no umlet class in it) but it looks like Umlets update check which cannot pass the firewall (so it should not be an problem with the JDK like the issue describes)

You can disable it by setting check_for_updates=false in your umlet.cfg

**Comment by ckaiser79** [comment]
Thanks for the hint with umlet.cfg. It solves my problem

**Comment by ckaiser79** [comment]
Just for completeness. Here is the complete stacktrace when try to run Umlet:

```
C:\devel\opt\Umlet>C:\coprogramme\java\jdk8u322-b06\bin\java.exe -D"log4j.configuration=file:log4j.properties" -jar umlet.jar
INFO  Program - Initializing Program: Version=15.0.0, Runtime=STANDALONE
INFO  Main - Initializing GUI ...
INFO  Main - GUI initialized
ERROR StartUpHelpText - Error at checking for new UMLet version
java.net.UnknownHostException: www.umlet.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at java.net.Socket.connect(Socket.java:556)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1228)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at java.net.URL.openStream(URL.java:1093)
        at com.baselet.gui.BrowserLauncher.readURL(BrowserLauncher.java:73)
        at com.baselet.diagram.UpdateCheckTimerTask.getNewVersionTextFromURL(UpdateCheckTimerTask.java:71)
        at com.baselet.diagram.UpdateCheckTimerTask.getNewVersionTextWithStartupHtmlFormat(UpdateCheckTimerTask.java:40)
        at com.baselet.diagram.UpdateCheckTimerTask.run(UpdateCheckTimerTask.java:30)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**Comment by ab78908** [comment]
I'm having similar issue and the problem is that UMlet not handling multi monitor setup correctly, I think it tries to show window outside of screen and it is not possible to reposition using shift + windows key  + arrows. Solution that works for me to edit AppData/Local/UMlet/umlet.cfg to change program_location to 0,0 and program_size to something small like 100,100 and then start the app and resize.
