### ISSUE TITLE
java.lang.NullPointerException when skrinking arrow to almost zero size.

### ISSUE THREAD

**Issue by jameshume** [umlet/umlet#694]
I am running on Ubuntu 18 (virtual machine running on VMware, windows 10 host):

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
Using umlet:

```
*******************************************
UMLet version 15.0.0 2022-04-26
Released under the terms of the GNU General Public License
Web: http://www.umlet.com/ Contact: [info@umlet.com](mailto:info@umlet.com)
*******************************************
```

When I shrink an arrow to what would make it flip direction, it approaches zero size before the flip, which I'm guessing might be the issue, I get the following null pointer exception:

```
$ umlet.sh
log4j:WARN No appenders could be found for logger (com.baselet.control.enums.Program).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.baselet.element.relation.helper.RelationPointList.getDragBox(RelationPointList.java:183)
	at com.baselet.element.relation.helper.RelationPointHandler.getDragBox(RelationPointHandler.java:144)
	at com.baselet.element.relation.helper.RelationPointHandler.drawCirclesAndDragBox(RelationPointHandler.java:167)
	at com.baselet.element.relation.Relation.resetAndDrawMetaDrawerContent(Relation.java:66)
	at com.baselet.element.NewGridElement.drawError(NewGridElement.java:135)
	at com.baselet.element.relation.Relation.drawError(Relation.java:164)
	at com.baselet.element.NewGridElement.updateModelFromText(NewGridElement.java:120)
	at com.baselet.element.relation.Relation.drag(Relation.java:97)
	at com.baselet.gui.command.Move.execute(Move.java:114)
	at com.baselet.gui.command.Macro.execute(Macro.java:22)
	at com.baselet.gui.command.Controller.executeCommand(Controller.java:26)
	at com.baselet.gui.listener.GridElementListener.dragEntity(GridElementListener.java:279)
	at com.baselet.gui.listener.GridElementListener.mouseDragged(GridElementListener.java:90)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6683)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3360)
	at java.desktop/java.awt.Component.processEvent(Component.java:6404)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4564)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.baselet.element.relation.helper.RelationPointList.getDragBox(RelationPointList.java:183)
	at com.baselet.element.relation.helper.RelationPointHandler.getDragBox(RelationPointHandler.java:144)
	at com.baselet.element.relation.helper.RelationPointHandler.isPointOverDragBox(RelationPointHandler.java:81)
	at com.baselet.element.relation.helper.RelationPointHandler.getSelection(RelationPointHandler.java:34)
	at com.baselet.element.relation.Relation.isSelectableOn(Relation.java:131)
	at com.baselet.element.ComponentSwing.contains(ComponentSwing.java:73)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2709)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.getChildAt(Container.java:2735)
	at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2721)
	at java.desktop/java.awt.Container.findComponentAt(Container.java:2691)
	at java.desktop/java.awt.Container$1.findComponentAt(Container.java:269)
	at java.desktop/sun.awt.GlobalCursorManager._updateCursor(GlobalCursorManager.java:193)
	at java.desktop/sun.awt.GlobalCursorManager.updateCursorImmediately(GlobalCursorManager.java:95)
	at java.desktop/sun.awt.X11.XComponentPeer.updateCursorImmediately(XComponentPeer.java:678)
	at java.desktop/java.awt.Component.updateCursorImmediately(Component.java:3225)
	at java.desktop/java.awt.Container.validate(Container.java:1669)
	at java.desktop/java.awt.GraphicsCallback$PeerPaintCallback.run(GraphicsCallback.java:83)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/java.awt.Component.paintAll(Component.java:3351)
<snip>
```

This is what I see on the screen:

![Umlet_Null_Pointer_Exception-2022-11-17_08 54 26](https://user-images.githubusercontent.com/3994844/202401279-8c980c48-bd9b-4aed-aa16-6f5ee9d5e5a5.gif)

**Comment by afdia** [comment]
Hi thanks for the report!
This looks like it's the same issue as #684

Could you please download the current "Umlet Standalone" build from https://github.com/umlet/umlet/actions/runs/3436175554 and test if it is fixed there?
Thanks!

**Comment by jameshume** [comment]
Hi, thanks, yes it is fixed in that version. Thanks for your help!
