### ISSUE TITLE
RuntimeException: Cannot load BuildInfo.properties

### ISSUE THREAD

**Issue by Om-i** [umlet/umlet#705]
I run java version 1.8.0_261
Umlet version 15.0

I double click on umlet.exe and it doesn't run.
I tried to run the jar file in cmd and this stack trace appears:
```
>java -jar Umlet.jar
Exception in thread "main" java.lang.RuntimeException: Cannot load BuildInfo.properties
        at com.baselet.control.util.Utils.readBuildInfo(Utils.java:193)
        at com.baselet.standalone.MainStandalone.readBuildInfoAndInitVersion(MainStandalone.java:312)
        at com.baselet.standalone.MainStandalone.initAll(MainStandalone.java:158)
        at com.baselet.standalone.MainStandalone.main(MainStandalone.java:146)
```
Do you have any idea what is this?
I also tried Umlet 14.3 and Java 19 with no result.

Thank You

**Comment by afdia** [comment]
Hi
I have not seen this error before, but most startup errors have to do with read/write access to Umlet files, so please check if the Umlet directory is located in a local directory (not a network share) where you have at least read access.

You could also check if the BuildInfo.properties file is available: It should be within the file libs/umlet-swing-15.0.0.jar (just rename it to .zip and check if the file exists)

**Comment by Om-i** [comment]
It was strange at first since the Umlet folder was placed in my desktop and it wasn't showing any permission error, but I moved the folders in C:\ and not it's working. Thanks for the insight!
