### ISSUE TITLE
UMLet says Java 6 is required

### ISSUE THREAD

**Issue by gerrycampion** [umlet/umlet#729]
When starting UMLet on a windows machine without Java, a notification says that Java 6 is required. I tried running with Java 6 and Java 7, but neither worked. After running with Java 8, UMLet starts up with no problems.

**Comment by afdia** [comment]
Java 6 is just the minimum requirement, but any later version works too.

Unfortunately the whole Java environment is getting more and more complicated with all the different distributions, but for Umlet you can use any Java or JDK distribution >=6. It doesnt matter if its the Oracle Java distribution or any OpenJDK like Temurin from https://adoptium.net/

**Comment by gerrycampion** [comment]
# More details

JRE 6 when running Umlet.exe
> Java Virtual Machine Launcher
Could not find the main class:
com.baselet.standalone.MainStandalone. Program will exit.

JRE 6 when running
> java -jar umlet.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/slf4j/LoggerFactory : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.baselet.standalone.MainStandalone.<clinit>(MainStandalone.java:38)
Could not find the main class: com.baselet.standalone.MainStandalone. Program will exit.

JRE 7 when running Umlet.exe:
> Java Virtual Machine Launcher
A Java Exception has occured.

JRE 7 when running
> java -jar umlet.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/slf4j/LoggerFactory : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.baselet.standalone.MainStandalone.<clinit>(MainStandalone.java:38)

**Comment by afdia** [comment]
To fix the issue we will recreate umlet.exe with the latest launch4j release and the min Java version should be set to 8, also updating the launch4j config for Umlet https://github.com/umlet/umlet/blob/master/umlet-standalone/src/exe/launch4j_project.xml

**Comment by afdia** [comment]
After the updates, Umlet still requires only JRE8 to run, but it can be built with JDK11 or JDK17 (but no longer JDK8)

Due to the complex nature of the project, several things are blocking in one or the other direction. E.g.:

- tycho (for Eclipse Plugin) cannot be updated or it will break JDK11, but without update JDK21 doesn't work
- findbugs updates may introduce new bug patterns
- Eclipse ECJ (compiler for custom elements) cannot be updated further or JRE8 for runtime is no longer possible
- npm and javaparser cannot be updated more without fixing an issue in code 

After more tests it shows that the gwt update from 2.9.0 to 2.10.0 breaks vscode with

> Access to script at 'http://localhost:39811/umletvscode/03936A1D532C55B4D702E62C1566DC60.cache.js' from origin 'vscode-webview://1ah4ns1okbgu45l41dhsej2olfi68hnqtq61dkar9eud60nd8fbr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by afdia** [comment]
The exe has been recreated with Launch4j v3.50 and uses the following logic:

1. use JAVA_HOME if set
2. check if PATH contains a java Installation
3. If both find no JRE, redirect to https://adoptium.net for JRE a download
